### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by nicemak** [naumanmir/filedownloadservice#1]
I followed everything u said, i added permission everything, but it gives download error on notification, My Tab Android version is KitKat 4.4.4

**Comment by nicemak** [comment]
this error only comes when i try to download .gif file, i tried .mp3 file and it worked fine

**Comment by nicemak** [comment]
also can u add notification after complete download?

**Comment by naumanmir** [comment]
@nicemak Gif file is not supported yet.

**Comment by naumanmir** [comment]
@nicemak i am closing this issue.
